FROM python:3.12.11 AS builder

WORKDIR /app
COPY . .

RUN pip3 install --progress-bar=on torch torchvision --index-url https://download.pytorch.org/whl/cu129
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple


